%function map_arg( input_args )

% Plot a map in a sps projection
% Andrea 11/1/06


axesm(...
         'MapProjection','eqdcylin',...
         'MapLonLimit',[-75 -50],...
         'MapLatLimit',[-55 -20],...
         'flatlimit', [-55 -20],...
         'parallellabel','on',...
         'meridianlabel','on',...
         'labelformat','compass',...
         'grid','on',...
         'MLabelParallel','south',...
         'fontsize',8);
    
load coast_argentina
plotm(latar,lonar,'k')
tightmap;
